<?php


namespace SilverStripe\GraphQL\Schema\Interfaces;

use SilverStripe\GraphQL\Schema\Field\ModelQuery;
use SilverStripe\GraphQL\Schema\Schema;

/**
 * A plugin that applies only to queries generated by models
 */
interface ModelQueryPlugin extends PluginInterface
{
    public function apply(ModelQuery $query, Schema $schema, array $config = []): void;
}
