<?php


namespace SilverStripe\GraphQL\Schema\Interfaces;

use SilverStripe\GraphQL\Schema\Schema;
use SilverStripe\GraphQL\Schema\Type\ModelType;

/**
 * A plugin that only applies to types generated by models
 */
interface ModelTypePlugin extends PluginInterface
{
    /**
     * @param ModelType $type
     * @param Schema $schema
     * @param array $config
     */
    public function apply(ModelType $type, Schema $schema, array $config = []): void;
}
