---
Name: graphql-dev
---
SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - SilverStripe\GraphQL\Extensions\DevBuildExtension

SilverStripe\Dev\DevelopmentAdmin:
  registered_controllers:
    graphql:
      controller: SilverStripe\GraphQL\Dev\DevelopmentAdmin
      links:
        graphql: 'List GraphQL development tools'
SilverStripe\GraphQL\Dev\DevelopmentAdmin:
  registered_controllers:
    build:
      controller: SilverStripe\GraphQL\Dev\Build
      links:
        build: Build the GraphQL schema
