---
Name: graphqlroutes
---
SilverStripe\Control\Director:
  rules:
    # Default admin route stage is draft
    graphql:
      Controller: 'SilverStripe\GraphQL\Controller'
      Stage: Stage
---
only:
  environment: 'dev'
---
SilverStripe\Control\Director:
  rules:
    'dev/graphiql': 'SilverStripe\GraphQL\GraphiQLController'
